### ISSUE TITLE
[v11] bounce management does not find any returned mail

### ISSUE THREAD

**Issue by rnakielski** [SSFGizmo/direct_mail#16]
We tried to use the bounce management with the v11 branch. We had test newsletters send to a not existing email. It could read the bounce mails in the mail account but does not update the statistics for returned mails without any log or error message.

**Comment by SSFGizmo** [comment]
fixed https://github.com/SSFGizmo/direct_mail/commit/0a7dfeec6aa5f4ce12283b5147e9bac99726e751
