### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by SSFGizmo** [SSFGizmo/direct_mail#2]
The TCA field 'sys_language_uid' of table 'sys_dmail' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'.

The TCA field 'sys_language_uid' of table 'sys_dmail_category' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'. 

in /typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1684 

* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.2/Feature-57082-NewTCATypeLanguage.html

**Comment by SSFGizmo** [comment]
TYPO3 Deprecation Notice: Module DirectMailNavFrame_DirectMail is using a "navigationFrameModule" configuration which renders an iframe for the navigation part, which is deprecated in favor of the navigationComponent functionality. The frame will be removed in TYPO3 v12.0. in /typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 871

**Comment by dmitryd** [comment]
Both these seems to be fixed in branch `11.x`:

https://github.com/SSFGizmo/direct_mail/blob/11.x/Configuration/TCA/sys_dmail.php#L21
https://github.com/SSFGizmo/direct_mail/blob/11.x/ext_tables.php#L55
