### ISSUE TITLE
Missing function sendTestMailToTable in Classes/Module/DmailController.php

### ISSUE THREAD

**Issue by abvdveen** [SSFGizmo/direct_mail#20]
When trying to send a testmail to a list of recipients in step 4 of the process, you get the error 'Call to undefined method DirectMailTeam\DirectMail\Module\DmailController::sendTestMailToTable()'

Copying this function from Classes/Module/Dmail.php fixes it.

**Comment by SSFGizmo** [comment]
https://github.com/SSFGizmo/direct_mail/commit/a746f3770e5f7fe24fc2bb708c328c8e9746987e

@abvdveen Would you please check?

**Comment by abvdveen** [comment]
@SSFGizmo Fine now, thanks.

**Comment by SSFGizmo** [comment]
fixed
