### ISSUE TITLE
Import recipients broken

### ISSUE THREAD

**Issue by abvdveen** [SSFGizmo/direct_mail#22]
Using the option 'Click here to import CSV' results in the error 'Call to a member function retrieveFileOrFolderObject() on null' in typo3/sysext/core/Classes/Utility/File/ExtendedFileUtility.php line 626.

This happens when using either the paste csv data option or the file upload option, after clicking 'Next' on the 'Import settings' page.

**Comment by SSFGizmo** [comment]
Do you see a new file under

* /fileadmin/user_upload/_temp_/
* DB: sys_file.uid
* Hidden Field
`<input type="hidden" name="CSV_IMPORT[newFileUid]" value="uid">`

**Comment by abvdveen** [comment]
Sorry, my fault: I hadn't checked out the latest code - apparently this has been fixed recently, thanks!
