### ISSUE TITLE
[11.x] getLanguageService could not be called statically

### ISSUE THREAD

**Issue by mediaessenz** [SSFGizmo/direct_mail#23]
The $GLOBALS['LANG'] was replaced by a new getLanguageService method with this commit:
https://github.com/SSFGizmo/direct_mail/commit/063e59681268f7d1e5aa8f53470cdf4e905b9825

Unfortunatelly this method is not marked as statically but used this way all over in the class.

[EDIT] It's in the 11-x branch, offcourse

**Comment by SSFGizmo** [comment]
Thx, fixed
