### ISSUE TITLE
[11.x] TempRepository::makeCategories and TempRepository::getRecordOverlay marked as static wrongly

### ISSUE THREAD

**Issue by mediaessenz** [SSFGizmo/direct_mail#24]
TempRepository::makeCategories and TempRepository::getRecordOverlay marked as static, but makeCategories using $this->getRecordOverlay inside.

Additional the class method is called as an object method.

e.g. inside DmailController line 1894:
```php
GeneralUtility::makeInstance(TempRepository::class)->makeCategories('tt_content', $row, $this->sys_language_uid)
```

Both methods should not marked as static.

**Comment by SSFGizmo** [comment]
Thx, fixed
