### ISSUE TITLE
Calendar in step 5 "Mass send" is not working

### ISSUE THREAD

**Issue by Apen** [SSFGizmo/direct_mail#29]
When i schedule a newsletter, in the step 5, in the "Distribution time" section , the calendar is not working.

**Comment by SSFGizmo** [comment]
`$this->pageRenderer->loadRequireJsModule('TYPO3/CMS/Backend/DateTimePicker');`

**Comment by SSFGizmo** [comment]
@Apen Would you please check?

**Comment by Apen** [comment]
Its works for me @SSFGizmo 👍
