### ISSUE TITLE
12.x - Function strftime() is deprecated

### ISSUE THREAD

**Issue by Apen** [SSFGizmo/direct_mail#57]
Hi,

First thanks for your work maintining direct_mail :-)
Then, i actuallty test the tree "12.x" and find this exception :

`PHP Runtime Deprecation Notice: Function strftime() is deprecated in "/vendor/directmailteam/direct-mail/Classes/Module/DmailController.php line 1511".`

Im on last TYPO3 12.

**Comment by SSFGizmo** [comment]
@Apen Thanks for the report, should be fixed now.

**Comment by Apen** [comment]
Good to me
